### ISSUE TITLE
Profile/edit profile

### ISSUE THREAD

**Issue by kmbeaulieu** [qwook/CMPE165-CharliesAngels#15]
Should we have a profile button on the top like with post a gig? Or should we leave it in the drop down menu and possibly have the edit profile in the settings page?

Do we have design plans for those?

**Comment by danieltannguyen** [comment]
I think it's ok for having a profile button in the drop down menu. Yesterday, I committed my branch by adding edit profile button in profile page. I will research about designs and hopefully I can give you guys a plan in a short time.

**Comment by qwook** [comment]
I'm thinking about emulating the facebook design for that and showing your name as the button to your profile.

**Comment by danieltannguyen** [comment]
that is a great idea, but you should do that later to save time for other MMF.
