### ISSUE TITLE
Applied to gigs

### ISSUE THREAD

**Issue by charlieshawfeather** [qwook/CMPE165-CharliesAngels#17]
Currently when you go to the page for a gig that you have already applied for the button still says "Apply", it is not until you try to apply again that it says that you have already applied. 

I think that there should be a check on the page loading that checks if the user has already applied or not. So that they don't have to click apply to find out that they have already applied.

**Comment by kmbeaulieu** [comment]
The apply button is disabled when you have applied already. So this is done :)
