### ISSUE TITLE
"Applications for" page hows wrong applicants

### ISSUE THREAD

**Issue by qwook** [qwook/CMPE165-CharliesAngels#22]
Click on **My Gigs** -> Click on **View Applicants**

What should be happening:
You are shown all the people who applied to your gig.

What is actually happening:
You are shown all the applications you made for other people's gigs.

**Comment by kmbeaulieu** [comment]
Yuuuup I realized that when I took a look at it last night, this is what I am going to be fixing tomorrow. I had it pulling in the same thing as my apps just so it pulled in _something_. Then I forgot about it and uploaded that code haha. It will get fixed with my next commit.

**Comment by kmbeaulieu** [comment]
this one is fixed on branch krystle
