### ISSUE TITLE
Any user can edit a gig post, even users not signed in.

### ISSUE THREAD

**Issue by qwook** [qwook/CMPE165-CharliesAngels#4]

**Comment by danieltannguyen** [comment]
I tried to use {{#if isLoggedIn}}
                    {{#if service.isUserEmployer}}
                         //edit button
                     {{#if service.isUserEmployer}}
                    {{#if isLoggedIn}}
it didn't work , it didn't show edit button for all users

**Comment by qwook** [comment]
Are you sure isLoggedIn is an actual function in meteor?
You need to use {{#if currentUser}} {{/if} instead

**Comment by kmbeaulieu** [comment]
Fixed it in my krystle branch with the latest push.
