### ISSUE TITLE
edit page, wage

### ISSUE THREAD

**Issue by kmbeaulieu** [qwook/CMPE165-CharliesAngels#7]
So if I don't edit the wage, it says I have no wage (even though it brought in the wage from the gig). I have to either type the same number in or put in a new wage. This should be a simple fix and you can work around it but it works nicer if you don't have to edit everything to reupload it (especially if we are stressed/timed when presenting our demo). It is just the wage that needs to be re input because of the $ I think.  

this _should _be super easy to fix (I think) but I can help if you can't figure it out right away.

**Comment by danieltannguyen** [comment]
It is fixed ! :) thanks QA
