### ISSUE TITLE
Post a Gig redirection

### ISSUE THREAD

**Issue by charlieshawfeather** [qwook/CMPE165-CharliesAngels#8]
I think that if the user is not logged in the when they click the post a gig it should redirect them to the login page.

Currently it takes the user to the post a gig page but they are not allowed to post a gig.

**Comment by kmbeaulieu** [comment]
What about not even displaying it if they aren't logged in? That is a super easy fix to do it that way.

**Comment by charlieshawfeather** [comment]
@kmweinrich Yeah that works. What do you think @codeskiller ?

**Comment by danieltannguyen** [comment]
Guys, I think @kmweinrich had a good idea. Let do that way. It is easy.

**Comment by kmbeaulieu** [comment]
I have it so when you are not logged in you cannot see post gig. It's on my krystle branch.
